---
- name: Install firewalld from RHEL
  yum:
    name: 'firewalld'
    state: present

- name: Make sure httpd is started at boot.
  service:
    name: firewalld
    enabled: true
    state: started

# SIMPL API
- firewalld:
    port: 8100/tcp
    permanent: true
    state: enabled
